//! narratarr.toml — configuration in the arr-bridge idiom: one file, a
//! [general] section plus one section per connected service, discovered at
//! /config/narratarr.toml (Docker) or ./narratarr.toml, generated by --init.
//! CLI flags override config values.

use serde::Deserialize;
use std::path::{Path, PathBuf};

pub const EXAMPLE: &str = r#"# narratarr.toml — the narrator for your bookshelf
#
# narratarr mirrors your ebook library into a monitored audiobook collection:
# it reads the books you own, matches each to its audiobook edition, and adds
# the matches to Listenarr. Ambiguous matches go to the review report; accept
# or reject them in the overrides file.

[general]
# How often to run a reconcile cycle. Comment out to run once and exit.
interval = "6h"

# Preferred audiobook language (ebook metadata lies; this is the truth).
language = "en"

# Safety: narratarr starts in dry-run and only reports what it WOULD do.
# Flip to true once the dry-run output looks right.
apply = false

# Ask Listenarr to search immediately when a book is added.
auto_search = false

# Process at most this many books per cycle. 0 = no limit.
limit = 0

# narratarr's only owned state: match decisions and retry timers.
state_file = "/config/narratarr.db"

# Written every cycle: what needs your review, with paste-ready override lines.
report_file = "/config/review.md"

# Your answers: `<ebook_key> = <ASIN>` to accept, `<ebook_key> = skip` to reject.
overrides_file = "/config/overrides.txt"

# Alternative ebook source: a directory of Calibre-style .opf sidecars.
# Only used when the [audiobookshelf] section is absent.
# books_dir = "/books"

[audiobookshelf]
# Server-to-server URLs should use container names, not host names.
url = "http://audiobookshelf:80"
token = "CHANGEME"
library = "Books"

[listenarr]
url = "http://listenarr:4545"
api_key = "CHANGEME"

# The review web UI: accept or reject ambiguous matches with cover art.
# LAN-facing and unauthenticated; do not expose it to the internet.
[web]
enabled = true
port = 4546
"#;

#[derive(Debug, Deserialize, Default)]
#[serde(default, deny_unknown_fields)]
pub struct Config {
    pub general: General,
    pub audiobookshelf: Option<Audiobookshelf>,
    pub listenarr: Option<Listenarr>,
    pub web: Option<Web>,
}

#[derive(Debug, Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct General {
    pub interval: Option<String>,
    pub language: String,
    pub apply: bool,
    pub auto_search: bool,
    pub limit: usize, // 0 = unlimited
    pub books_dir: Option<String>,
    pub state_file: Option<String>,
    pub report_file: Option<String>,
    pub overrides_file: Option<String>,
}

impl Default for General {
    fn default() -> Self {
        Self {
            interval: None,
            language: "en".into(),
            apply: false,
            auto_search: false,
            limit: 0,
            books_dir: None,
            state_file: None,
            report_file: None,
            overrides_file: None,
        }
    }
}

#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Audiobookshelf {
    pub url: String,
    pub token: String,
    pub library: String,
}

#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Listenarr {
    pub url: String,
    pub api_key: String,
}

#[derive(Debug, Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct Web {
    pub enabled: bool,
    pub port: u16,
}

impl Default for Web {
    fn default() -> Self {
        Self {
            enabled: false,
            port: 4546,
        }
    }
}

pub fn load(path: &Path) -> Result<Config, String> {
    let text = std::fs::read_to_string(path)
        .map_err(|e| format!("cannot read {}: {e}", path.display()))?;
    toml::from_str(&text).map_err(|e| format!("invalid config {}: {e}", path.display()))
}

/// Conventional locations, most-Docker-like first.
pub fn discover() -> Option<PathBuf> {
    ["/config/narratarr.toml", "narratarr.toml"]
        .iter()
        .map(PathBuf::from)
        .find(|p| p.exists())
}
